### ISSUE TITLE
向量、稀疏矩阵模板化通用接口Vector及SparseMatrix实现原理（留档用）

### ISSUE THREAD

**Issue by Riiiichman-Li** [CDCS-HPC/ChipSum#4]
ChipSum主框架的实现方案为高阶过程，数据（如向量的数据、稀疏矩阵的邻接表等）采用抽象类型特性实现，过程则采用重载和可变参数模板等特性实现。这里我未来将抽时间解释一下具体实现机制。
// TODO

**Comment by gassive** [comment]
merge前把所有的issue都close掉
